# Generated by Django 3.2.6 on 2021-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70)),
                ('fname', models.CharField(default='', max_length=25)),
                ('lname', models.CharField(default='', max_length=15)),
                ('pwd', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
